GENERAL_CHART_TITLE = 'Ciężar według dni'
EXERCISE_CHART_TITLE = 'Aktywność w ćwiczeniu: %s'
NO_DATA = 'Brak danych \"%s\"!!'
CONTACT_COACH = 'Kontakt do trenera'
ASK_COACH = 'Poproś o pomoc trenera'
